### ISSUE TITLE
need uppercase `interface` when creating typings

### ISSUE THREAD

**Issue by GeoSkyGPS** [open-rpc/typings#127]
When declaring a param as object in openRPC.json.

running typings creates interface with lower case `I` and circleCI is not happy with it.

![](https://cdn.discordapp.com/attachments/550473819266220042/621007120384655370/unknown.png)

```
ERROR: /home/circleci/project/__GENERATED_TYPES__/index.ts:16:18 - interface name must start with a capitalized I
```

**Comment by BelfordZ** [comment]
nit: the case/format for the name OpenRPC should follow one of the following: OpenRPC, openrpc, open-rpc. Use which ever is applicable. Ofc its your choice to name it how ever you like, but it would be best if we all use the same variants.

**Comment by BelfordZ** [comment]
A simple fix for the underlying issue would be to loosen the tslint requirement for interface namin.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/interface-name-prefix.md

https://github.com/open-rpc/generator-client/blob/master/templates/typescript/static/tslint.json#L12 change to false, remove options

**Comment by shanejonas** [comment]
the tslint for the project using it would needs
 that change, not the generated client tslint itself

**Comment by shanejonas** [comment]
in this case it’s pristine

**Comment by BelfordZ** [comment]
fixed in latest release
