### ISSUE TITLE
Duplicate typings in typescript

### ISSUE THREAD

**Issue by BelfordZ** [open-rpc/typings#42]
currently .toString is returning duplicate type names.

We should handle this in the same way it was dealt with in rust

**Comment by Wodann** [comment]
When generating rust bindings, I discovered it does still result in duplicates. I'm curious whether this a regression or caused by a different problem?

This is the openrpc.json that I used: https://raw.githubusercontent.com/ethereum/execution-apis/v1.0.0-beta.1/refs-openrpc.json
